[tools]
direnv = "latest"
"github:cli/cli" = "latest"
gitleaks = "latest"
jq = "latest"
node = "latest"
"ubi:dapi/port-selector" = "latest"
ruby = "3.4.8"
"npm:playwright-cli" = "latest"
go = "1.26.2"

[task_config]
includes = [".mise/tasks/*.toml"]
